
import complementos.apiClientes;
import java.awt.Cursor;
import static java.awt.Frame.WAIT_CURSOR;
import java.awt.Point;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import org.json.JSONArray;
import org.json.JSONException;
import org.json.JSONObject;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Desarrollo
 */
public class ModificarAutorizados extends javax.swing.JFrame {

/**
     * Creates new form ModificarAutorizados
     */
    //variables
   
        apiClientes apiclientes=new apiClientes();
        //public static String codigoMacroSelect;
        public static String cod_macro;
        String idAutorizado="";
        public static Integer pantalla;
    public ModificarAutorizados() {
        initComponents();
        this.setLocationRelativeTo(null);
        rsscalelabel.RSScaleLabel.setScaleLabel(lbl_guardar, "src/images/save.png");
        rsscalelabel.RSScaleLabel.setScaleLabel(lbl_agregar, "src/images/plus.png");
        rsscalelabel.RSScaleLabel.setScaleLabel(lbl_editar, "src/images/register.png");
        rsscalelabel.RSScaleLabel.setScaleLabel(lbl_ok, "src/images/tick.png");
        rsscalelabel.RSScaleLabel.setScaleLabel(lbl_busqueda, "src/images/lupa.png");
        if(pantalla==0)
        {
            System.out.println("viene de home");
            txt_codigo.requestFocus();
        }
        if(pantalla==1)
        {
           System.out.println("viene de autorizados"); 
           txt_codigo.setText(cod_macro);
           consultarCodigo();
           
        }
        if(pantalla==2)
        {
           System.out.println("viene de editar"); 
           txt_codigo.setText(cod_macro);
           consultarCodigo();
        }
        if(pantalla==3)
        {
            System.out.println("viene de buscar"); 
            txt_codigo.setText(cod_macro);
           consultarCodigo();
        }
        tb_autorizados.addMouseListener(new MouseAdapter(){
            public void mousePressed(MouseEvent mouse_evt)
                {
                    JTable tb=(JTable)mouse_evt.getSource();
                    Point point = mouse_evt.getPoint();
                    int row=tb.rowAtPoint(point);
                    idAutorizado=tb.getValueAt(tb.getSelectedRow(), 0).toString();
                    //System.out.println(""+row);
                    //System.out.println(""+codigoMacroSelect);
                }
        });
        //System.out.println("Codigo Macro select "+codigoMacroSelect);
       
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_ok = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lbl_busqueda = new javax.swing.JLabel();
        txt_codigo = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        txt_nombre = new javax.swing.JTextField();
        txt_materno = new javax.swing.JTextField();
        txt_paterno = new javax.swing.JTextField();
        txt_puesto = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lbl_guardar = new javax.swing.JLabel();
        lbl_agregar = new javax.swing.JLabel();
        lbl_editar = new javax.swing.JLabel();
        btn_consultar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_comentarios = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        tb_autorizados = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Editar Cliente");
        setPreferredSize(new java.awt.Dimension(700, 500));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_ok.setText("jLabel7");
        getContentPane().add(lbl_ok, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 15, 30, 30));

        jLabel1.setText("Codigo MacroPro:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        lbl_busqueda.setText("jLabel7");
        getContentPane().add(lbl_busqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 15, 30, 30));

        txt_codigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_codigoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_codigoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_codigoKeyTyped(evt);
            }
        });
        getContentPane().add(txt_codigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 100, -1));

        jButton1.setText("Buscar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 5, 50, 50));

        txt_nombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_nombreKeyReleased(evt);
            }
        });
        getContentPane().add(txt_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 100, -1));

        txt_materno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_maternoKeyReleased(evt);
            }
        });
        getContentPane().add(txt_materno, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 60, 100, -1));

        txt_paterno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_paternoKeyReleased(evt);
            }
        });
        getContentPane().add(txt_paterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 60, 100, -1));

        txt_puesto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_puestoKeyReleased(evt);
            }
        });
        getContentPane().add(txt_puesto, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 100, -1));

        jLabel2.setText("Nombre:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, -1, -1));

        jLabel3.setText("Apellido Paterno:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 60, -1, -1));

        jLabel4.setText("Apellido Materno:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 60, -1, -1));

        jLabel5.setText("Puesto:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, -1));

        jLabel6.setText("Comentarios:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 100, -1, -1));

        lbl_guardar.setText("jLabel7");
        getContentPane().add(lbl_guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 220, 30, 30));

        lbl_agregar.setText("jLabel7");
        getContentPane().add(lbl_agregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 220, 30, 30));

        lbl_editar.setText("jLabel7");
        getContentPane().add(lbl_editar, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 220, 30, 30));

        btn_consultar.setText("Consultar");
        btn_consultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_consultarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_consultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 5, 50, 50));

        txt_comentarios.setColumns(20);
        txt_comentarios.setRows(5);
        txt_comentarios.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_comentariosKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(txt_comentarios);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 100, 306, -1));

        tb_autorizados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre", "Estatus"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tb_autorizados);
        if (tb_autorizados.getColumnModel().getColumnCount() > 0) {
            tb_autorizados.getColumnModel().getColumn(0).setMinWidth(30);
            tb_autorizados.getColumnModel().getColumn(0).setPreferredWidth(30);
            tb_autorizados.getColumnModel().getColumn(0).setMaxWidth(30);
            tb_autorizados.getColumnModel().getColumn(2).setMinWidth(60);
            tb_autorizados.getColumnModel().getColumn(2).setPreferredWidth(60);
            tb_autorizados.getColumnModel().getColumn(2).setMaxWidth(60);
        }

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 204, -1, 144));

        jButton3.setText("Editar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 210, 50, 50));

        jButton4.setText("Agregar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 210, 50, 50));

        jButton5.setText("Guardar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 210, 50, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_consultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_consultarActionPerformed
        // TODO add your handling code here:
        if(txt_codigo.isEditable())
        {
            limpiarCampos();
        if(txt_codigo.getText().equalsIgnoreCase(""))
        {
            cuadroDialogo("Ingrese Codigo");
        }
        else
        {
            
            consultarCodigo();            
            //cuadroDialogo(respuesta.toString());
        }
        }
        else
        {
            txt_codigo.setEditable(true);
            txt_codigo.setText("");
            txt_codigo.setFocusable(true);
            limpiarCampos();
        }
        
    }//GEN-LAST:event_btn_consultarActionPerformed

    public void consultarCodigo()
    {
        try{
            this.setCursor(new Cursor(WAIT_CURSOR));
        JSONObject respuesta=new JSONObject();
            JSONObject resCli=new JSONObject();
             
            respuesta=apiclientes.getCliente(txt_codigo.getText().toString().trim());
            if(respuesta.getBoolean("success"))
            {
                DefaultTableModel modelo = (DefaultTableModel)tb_autorizados.getModel();
                txt_codigo.setEditable(false);
                //btn_consultar.setText("habilitar");
                JSONArray jArray = respuesta.getJSONArray("respuesta");
                 for (int i=0;i<jArray.length();i++){
                        resCli = jArray.getJSONObject(i);       
                }
                 JSONArray arrayAu = respuesta.getJSONArray("autorizados");
                 System.out.println("array autorizados lengh "+arrayAu.length());
                 for (int i=0;i<arrayAu.length();i++){
                        //resCli = arrayAu.getJSONObject(i);    
                        JSONObject obj=arrayAu.getJSONObject(i);
                        String nombre=obj.getString("nombre")+" "+obj.getString("a_paterno")+" "+obj.getString("a_materno");
                        String estatus=obj.getString("nom_estatus");
                        Integer id=obj.getInt("idautorizados");
                        Object [] fila = new Object[3];
                        fila[0] = id;
                        fila[1] = nombre;
                        fila[2] = estatus;
                        modelo.addRow ( fila );
                        System.out.println("autorizados:"+obj);
                }
            txt_nombre.setText(resCli.getString("nombre"));
            txt_paterno.setText(resCli.getString("a_paterno"));
            txt_materno.setText(resCli.getString("a_materno"));
            txt_puesto.setText(resCli.getString("puesto"));
            txt_comentarios.setText(resCli.getString("comentarios"));
            tb_autorizados.setModel(modelo);
            }
        }
        catch(Exception e)
        {
            System.err.println(e.getMessage());
        }
        finally{
            this.setCursor(new Cursor(DEFAULT_CURSOR));
        }
        
            
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        //JSONObject res =  apiclientes.getClientes();
        //cuadroDialogo(res.toString());
       //this.setCursor(new Cursor(WAIT_CURSOR));
        BuscarClientes vistaBC=new BuscarClientes();
        vistaBC.setVisible(true);
        // this.setCursor(new Cursor(DEFAULT_CURSOR));
        this.setVisible(false);
       
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txt_nombreKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_nombreKeyReleased
        // TODO add your handling code here:
        txt_nombre.setText(txt_nombre.getText().toUpperCase());
    }//GEN-LAST:event_txt_nombreKeyReleased

    private void txt_paternoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_paternoKeyReleased
        // TODO add your handling code here:
        txt_paterno.setText(txt_paterno.getText().toUpperCase());
    }//GEN-LAST:event_txt_paternoKeyReleased

    private void txt_maternoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_maternoKeyReleased
        // TODO add your handling code here:
        txt_materno.setText(txt_materno.getText().toUpperCase());
    }//GEN-LAST:event_txt_maternoKeyReleased

    private void txt_puestoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_puestoKeyReleased
        // TODO add your handling code here:
        txt_puesto.setText(txt_puesto.getText().toUpperCase());
    }//GEN-LAST:event_txt_puestoKeyReleased

    private void txt_comentariosKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_comentariosKeyReleased
        // TODO add your handling code here:
        txt_comentarios.setText(txt_comentarios.getText().toUpperCase());
    }//GEN-LAST:event_txt_comentariosKeyReleased

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        if(idAutorizado.equalsIgnoreCase(""))
        {
            cuadroDialogo("No ha seleccionado autorizado");
        }
        else
        {
            EditarAutorizado veditar=null;
            
            veditar.id=Integer.parseInt(idAutorizado);
            veditar.cod_mac=txt_codigo.getText().toUpperCase();
            veditar=new EditarAutorizado();
            veditar.setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        home v_home=new home();
        v_home.setVisible(true);
    }//GEN-LAST:event_formWindowClosed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        if(txt_codigo.getText().equalsIgnoreCase(""))
        {
            cuadroDialogo("Ingrese Codigo");
        }
        else
        {
            if(apiclientes.modificarCliente(crearJson()))
            {
            
            }
        }
        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        if(txt_codigo.getText().equalsIgnoreCase(""))
        {
            cuadroDialogo("Consulte Cliente");
        }
        else
        {
            Autorizado vista=null;
            vista.param=txt_codigo.getText().toString().trim();
            vista.pantalla=1;
            vista=new Autorizado(); 
            vista.setVisible(true);
            this.setVisible(false);
        }
        
    }//GEN-LAST:event_jButton4ActionPerformed
private int limite  = 10;
    private void txt_codigoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_codigoKeyReleased
        // TODO add your handling code here:
        txt_codigo.setText(txt_codigo.getText().toUpperCase());
    }//GEN-LAST:event_txt_codigoKeyReleased

    private void txt_codigoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_codigoKeyTyped
        // TODO add your handling code here:
        if (txt_codigo.getText().length()== limite)
     evt.consume();
    }//GEN-LAST:event_txt_codigoKeyTyped

    private void txt_codigoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_codigoKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==10)
        {
            if(txt_codigo.getText().equalsIgnoreCase(""))
            {
                cuadroDialogo("Ingrese codigo");
            }
            else
            {
                
            }
        }
        
    }//GEN-LAST:event_txt_codigoKeyPressed

    public JSONObject crearJson()
    {
        JSONObject obj = new JSONObject();
        try {
            obj.put("codigoMacro",txt_codigo.getText().trim());
            obj.put("nombre", txt_nombre.getText().trim());
            obj.put("a_paterno",txt_paterno.getText().trim());
            obj.put("a_materno", txt_materno.getText().trim());
            obj.put("puesto",txt_puesto.getText().trim());
            obj.put("comentarios", txt_comentarios.getText().trim());
            }
        catch (JSONException e)
            {
             System.err.println("error al crear JSON:"+e.getMessage());  
            }
        return obj;
    }
    public void limpiarCampos()
    {
        txt_nombre.setText("");
        txt_paterno.setText("");
        txt_materno.setText("");
        txt_puesto.setText("");
        txt_comentarios.setText("");
        DefaultTableModel modelo = (DefaultTableModel)tb_autorizados.getModel();
        if(modelo.getRowCount()>0)
        {
            modelo.getDataVector().removeAllElements();
            modelo.fireTableDataChanged();
        }
        
    }
    public void cuadroDialogo(String mensaje)
    {
          JOptionPane.showMessageDialog(null, mensaje);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModificarAutorizados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModificarAutorizados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModificarAutorizados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModificarAutorizados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModificarAutorizados().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_consultar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbl_agregar;
    private javax.swing.JLabel lbl_busqueda;
    private javax.swing.JLabel lbl_editar;
    private javax.swing.JLabel lbl_guardar;
    private javax.swing.JLabel lbl_ok;
    private javax.swing.JTable tb_autorizados;
    private javax.swing.JTextField txt_codigo;
    private javax.swing.JTextArea txt_comentarios;
    private javax.swing.JTextField txt_materno;
    private javax.swing.JTextField txt_nombre;
    private javax.swing.JTextField txt_paterno;
    private javax.swing.JTextField txt_puesto;
    // End of variables declaration//GEN-END:variables
}
